export interface CropInfo {
  name: string;
  scientificName: string;
  seasons: ('kharif' | 'rabi' | 'zaid')[];
  sowingTime: string;
  harvestTime: string;
  idealTemp: string;
  waterNeed: 'low' | 'medium' | 'high';
  icon: string;
  color: string;
  notes: string;
}

export const CROPS: CropInfo[] = [
  {
    name: 'Rice (Paddy)',
    scientificName: 'Oryza sativa',
    seasons: ['kharif'],
    sowingTime: 'June – July',
    harvestTime: 'October – November',
    idealTemp: '22–32°C',
    waterNeed: 'high',
    icon: 'Wheat',
    color: 'from-primary-400 to-primary-600',
    notes: 'Needs standing water. Sow with the monsoon onset.',
  },
  {
    name: 'Wheat',
    scientificName: 'Triticum aestivum',
    seasons: ['rabi'],
    sowingTime: 'November – December',
    harvestTime: 'March – April',
    idealTemp: '10–25°C',
    waterNeed: 'medium',
    icon: 'Wheat',
    color: 'from-secondary-400 to-secondary-600',
    notes: 'Cool-season staple. Needs 4–5 irrigations.',
  },
  {
    name: 'Maize (Corn)',
    scientificName: 'Zea mays',
    seasons: ['kharif', 'zaid'],
    sowingTime: 'June – July / Feb – Mar',
    harvestTime: 'Oct – Nov / May – Jun',
    idealTemp: '18–30°C',
    waterNeed: 'medium',
    icon: 'Sprout',
    color: 'from-secondary-500 to-primary-500',
    notes: 'Grown in both kharif and zaid seasons.',
  },
  {
    name: 'Tomato',
    scientificName: 'Solanum lycopersicum',
    seasons: ['rabi', 'zaid'],
    sowingTime: 'Oct – Nov / Feb – Mar',
    harvestTime: 'Jan – Mar / May – Jul',
    idealTemp: '20–28°C',
    waterNeed: 'medium',
    icon: 'Cherry',
    color: 'from-error-400 to-error-600',
    notes: 'Sensitive to frost and waterlogging.',
  },
  {
    name: 'Cotton',
    scientificName: 'Gossypium hirsutum',
    seasons: ['kharif'],
    sowingTime: 'May – June',
    harvestTime: 'Nov – Jan',
    idealTemp: '22–32°C',
    waterNeed: 'medium',
    icon: 'Cloud',
    color: 'from-neutral-300 to-neutral-500',
    notes: 'Needs warm climate with dry harvest period.',
  },
  {
    name: 'Sugarcane',
    scientificName: 'Saccharum officinarum',
    seasons: ['kharif', 'rabi'],
    sowingTime: 'Feb – Mar / Oct – Nov',
    harvestTime: '12–18 months later',
    idealTemp: '25–35°C',
    waterNeed: 'high',
    icon: 'Sprout',
    color: 'from-primary-500 to-primary-700',
    notes: 'Long-duration crop. Regular irrigation needed.',
  },
  {
    name: 'Groundnut (Peanut)',
    scientificName: 'Arachis hypogaea',
    seasons: ['kharif', 'zaid'],
    sowingTime: 'June – July / Jan – Feb',
    harvestTime: 'Oct – Nov / May – Jun',
    idealTemp: '22–28°C',
    waterNeed: 'low',
    icon: 'CircleDot',
    color: 'from-secondary-600 to-secondary-800',
    notes: 'Drought-tolerant. Needs well-drained soil.',
  },
  {
    name: 'Mustard',
    scientificName: 'Brassica juncea',
    seasons: ['rabi'],
    sowingTime: 'October – November',
    harvestTime: 'Feb – Mar',
    idealTemp: '15–25°C',
    waterNeed: 'low',
    icon: 'Flower2',
    color: 'from-secondary-400 to-secondary-600',
    notes: 'Cool-season oilseed. 1–2 irrigations suffice.',
  },
  {
    name: 'Cucumber',
    scientificName: 'Cucumis sativus',
    seasons: ['zaid'],
    sowingTime: 'March – April',
    harvestTime: 'May – June',
    idealTemp: '25–35°C',
    waterNeed: 'medium',
    icon: 'Sprout',
    color: 'from-primary-300 to-primary-500',
    notes: 'Summer crop. Needs warm soil and sunshine.',
  },
  {
    name: 'Watermelon',
    scientificName: 'Citrullus lanatus',
    seasons: ['zaid'],
    sowingTime: 'Feb – March',
    harvestTime: 'May – June',
    idealTemp: '25–35°C',
    waterNeed: 'medium',
    icon: 'Circle',
    color: 'from-success-400 to-success-600',
    notes: 'Loves heat. Needs sandy, well-drained soil.',
  },
  {
    name: 'Pulses (Lentil)',
    scientificName: 'Lens culinaris',
    seasons: ['rabi'],
    sowingTime: 'Nov – Dec',
    harvestTime: 'Feb – Mar',
    idealTemp: '15–25°C',
    waterNeed: 'low',
    icon: 'Sprout',
    color: 'from-primary-400 to-primary-600',
    notes: 'Fixes nitrogen. Good for depleted soils.',
  },
  {
    name: 'Soybean',
    scientificName: 'Glycine max',
    seasons: ['kharif'],
    sowingTime: 'June – July',
    harvestTime: 'Oct – Nov',
    idealTemp: '20–30°C',
    waterNeed: 'medium',
    icon: 'Sprout',
    color: 'from-primary-500 to-primary-700',
    notes: 'Protein-rich pulse. Improves soil fertility.',
  },
];

export const SEASON_INFO: Record<'kharif' | 'rabi' | 'zaid', { name: string; months: string; desc: string }> = {
  kharif: { name: 'Kharif (Monsoon)', months: 'June – October', desc: 'Sown with the monsoon rains and harvested in autumn.' },
  rabi: { name: 'Rabi (Winter)', months: 'November – March', desc: 'Sown after the monsoon and harvested in spring.' },
  zaid: { name: 'Zaid (Summer)', months: 'March – June', desc: 'Short summer season between rabi and kharif.' },
};
